Área de Trabalho/AplicacaoRails/restaurante/config/routes.rb
Restaurante::Application.routes.draw do
  resources :itempedidos

  resources :pedidos

  resources :motoboys

  resources :clientes

  resources :cardapios

end

Área de Trabalho/AplicacaoRails/restaurante/app/models/cardapio.rb
class Cardapio < ActiveRecord::Base
  attr_accessible :descricao, :nome, :preco
end

Área de Trabalho/AplicacaoRails/restaurante/app/models/cliente.rb
class Cliente < ActiveRecord::Base
  attr_accessible :endereco, :nome
end

Área de Trabalho/AplicacaoRails/restaurante/app/models/itempedido.rb
class Itempedido < ActiveRecord::Base
  belongs_to :pedido
  belongs_to :cardapio
  attr_accessible :quantidade, :pedido_id, :cardapio_id
end

Área de Trabalho/AplicacaoRails/restaurante/app/models/motoboy.rb
class Motoboy < ActiveRecord::Base
  attr_accessible :nome, :telefone
end

Área de Trabalho/AplicacaoRails/restaurante/app/models/pedido.rb
class Pedido < ActiveRecord::Base
  belongs_to :cliente
  belongs_to :motoboy
  attr_accessible :data, :hora, :valor, :cliente_id, :motoboy_id
end

Área de Trabalho/AplicacaoRails/restaurante/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Área de Trabalho/AplicacaoRails/restaurante/app/controllers/cardapios_controller.rb
class CardapiosController < InheritedResources::Base
end

Área de Trabalho/AplicacaoRails/restaurante/app/controllers/clientes_controller.rb
class ClientesController < InheritedResources::Base
end

Área de Trabalho/AplicacaoRails/restaurante/app/controllers/itempedidos_controller.rb
class ItempedidosController < InheritedResources::Base
end

Área de Trabalho/AplicacaoRails/restaurante/app/controllers/motoboys_controller.rb
class MotoboysController < InheritedResources::Base
end

Área de Trabalho/AplicacaoRails/restaurante/app/controllers/pedidos_controller.rb
class PedidosController < InheritedResources::Base
end

Área de Trabalho/AplicacaoRails/restaurante/app/helpers/application_helper.rb
module ApplicationHelper
end

Área de Trabalho/AplicacaoRails/restaurante/app/helpers/cardapios_helper.rb
module CardapiosHelper
end

Área de Trabalho/AplicacaoRails/restaurante/app/helpers/clientes_helper.rb
module ClientesHelper
end

Área de Trabalho/AplicacaoRails/restaurante/app/helpers/home_helper.rb
module HomeHelper
end

Área de Trabalho/AplicacaoRails/restaurante/app/helpers/itempedidos_helper.rb
module ItempedidosHelper
end

Área de Trabalho/AplicacaoRails/restaurante/app/helpers/motoboys_helper.rb
module MotoboysHelper
end

Área de Trabalho/AplicacaoRails/restaurante/app/helpers/pedidos_helper.rb
module PedidosHelper
end

Área de Trabalho/AplicacaoRails/restaurante/app/views/cardapios/_form.html.haml
= semantic_form_for [@cardapio] do |form|
  = form.input :nome, :label => 'Nome' 
  = form.input :descricao, :label => 'Descricao'
  = form.input :preco, :label => 'Preco'
  = form.submit 'Salvar'

Área de Trabalho/AplicacaoRails/restaurante/app/views/cardapios/edit.html.erb
<h1>Editing cardapio</h1>

<%= render 'form' %>

<%= link_to 'Show', @cardapio %> |
<%= link_to 'Back', cardapios_path %>

Área de Trabalho/AplicacaoRails/restaurante/app/views/cardapios/index.html.erb
<h1>Cardapio</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Descricao</th>
    <th>Preco</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cardapios.each do |cardapio| %>
  <tr>
    <td><%= cardapio.nome %></td>
    <td><%= cardapio.descricao %></td>
    <td><%= cardapio.preco %></td>
    <td><%= link_to 'Show', cardapio %></td>
    <td><%= link_to 'Edit', (edit_cardapio_path cardapio) %></td>
    <td><%= link_to 'Excluir', cardapio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cardapio', new_cardapio_path %>

Área de Trabalho/AplicacaoRails/restaurante/app/views/cardapios/new.html.erb
<h1>New cardapio</h1>

<%= render 'form' %>

<%= link_to 'Back', cardapios_path %>

Área de Trabalho/AplicacaoRails/restaurante/app/views/cardapios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @cardapio.nome %>
</p>

<p>
  <b>Descricao:</b>
  <%= @cardapio.descricao %>
</p>

<p>
  <b>Preco:</b>
  <%= @cardapio.preco %>
</p>


<%= link_to 'Edit', (edit_cardapio_path (@cardapio)) %> |
<%= link_to 'Back', (cardapios_path) %>

Área de Trabalho/AplicacaoRails/restaurante/app/views/clientes/_form.html.haml
= semantic_form_for [@cliente] do |form|
  = form.input :nome, :label => 'Nome' 
  = form.input :endereco, :label => 'Endereco'
  = form.submit 'Salvar'

Área de Trabalho/AplicacaoRails/restaurante/app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

Área de Trabalho/AplicacaoRails/restaurante/app/views/clientes/index.html.erb
<h1>Clientes</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Endereco</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clientes.each do |cliente| %>
  <tr>
    <td><%= cliente.nome %></td>
    <td><%= cliente.endereco %></td>
    <td><%= link_to 'Show', cliente %></td>
    <td><%= link_to 'Edit', (edit_cliente_path cliente) %></td>
    <td><%= link_to 'Excluir', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cliente', new_cliente_path %>

Área de Trabalho/AplicacaoRails/restaurante/app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

Área de Trabalho/AplicacaoRails/restaurante/app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @cliente.nome %>
</p>

<p>
  <b>Endereco:</b>
  <%= @cliente.endereco %>
</p>


<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

Área de Trabalho/AplicacaoRails/restaurante/app/views/home/index.html.erb
<h1>Restaurante Delivery</h1>
<p>By Valeria Cordeiro</p>



<h2>Seja Bem-Vindo!</h2>

Área de Trabalho/AplicacaoRails/restaurante/app/views/itempedidos/_form.html.haml
= semantic_form_for [@itempedido] do |form|

  = form.input :quantidade, :label => 'Quantidade'
  = form.input :pedido, :member_label => :data, :label => 'Pedido'
  = form.input :cardapio, :member_label => :nome, :label => 'Cardapio'
  = form.submit 'Salvar'

Área de Trabalho/AplicacaoRails/restaurante/app/views/itempedidos/edit.html.erb
<h1>Editing itempedido</h1>

<%= render 'form' %>

<%= link_to 'Show', @itempedido %> |
<%= link_to 'Back', itempedidos_path %>

Área de Trabalho/AplicacaoRails/restaurante/app/views/itempedidos/index.html.erb
<h1>Itens</h1>

<table>
  <tr>
    <th>Quantidade</th>
    <th>Pedido</th>
    <th>Cardapio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @itempedidos.each do |itempedido| %>
  <tr>
    <td><%= itempedido.quantidade %></td>
    <td><%= itempedido.pedido.data %></td>
    <td><%= itempedido.cardapio.nome %></td>
    <td><%= link_to 'Show', itempedido %></td>
    <td><%= link_to 'Edit', (edit_itempedido_path itempedido) %></td>
    <td><%= link_to 'Excluir', itempedido, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Itempedido', new_itempedido_path %>

Área de Trabalho/AplicacaoRails/restaurante/app/views/itempedidos/new.html.erb
<h1>New itempedido</h1>

<%= render 'form' %>

<%= link_to 'Back', itempedidos_path %>

Área de Trabalho/AplicacaoRails/restaurante/app/views/itempedidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Quantidade:</b>
  <%= @itempedido.quantidade %>
</p>

<p>
  <b>Pedido:</b>
  <%= @itempedido.pedido.data %>
</p>

<p>
  <b>Cardapio:</b>
  <%= @itempedido.cardapio.nome %>
</p>


<%= link_to 'Edit', edit_itempedido_path(@itempedido) %> |
<%= link_to 'Back', itempedidos_path %>

Área de Trabalho/AplicacaoRails/restaurante/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurante</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Área de Trabalho/AplicacaoRails/restaurante/app/views/layouts/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 3.0 License

Name       : Dangled  
Description: A two-column, fixed-width design with a dark color scheme.
Version    : 1.0
Released   : 20120807
-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <title>Restaurante</title>
  <%= stylesheet_link_tag :default %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper">
	<div id="menu">

		<ul>
			       <li><%= link_to 'Cliente',clientes_path %></li>
			       <li><%= link_to 'Motoboy',motoboys_path %></li>
			       <li><%= link_to 'Cardapio',cardapios_path %></li>
			       <li><%= link_to 'Pedido',pedidos_path %></li>
			       <li><%= link_to 'Itempedido',itempedidos_path %></li>
		</ul>
	</div>
	<!-- end #menu -->
        <div id="header">
		<div id="logo">
		
		       <h1><b href="/">Restaurante Delivery</b>&nbsp;&nbsp;&nbsp;<span>by Valeria Cordeiro</span></h1>
		</div>
	</div>
	<!-- end #header -->
	<div id="page">
		<div class="post"><img src="assets/img4.jpg" alt="" width="120" height="160" class="float" />
                <div class="post">
			<h2 class="title">Seja Bem-Vindo </h2>
			
			<%= yield %>
		<div style="clear: both;">&nbsp;</div>
        </div>
	<div id="footer">
		<p>&copy; Sitename. All rights reserved. Design by <a href="http://www.freecsstemplates.org/">FCT</a>. Photos by <a href="http://fotogrph.com/">Fotogrph</a>.</p>
	</div>
	<!-- end #footer --> 
</div>
</body>
</html>

Área de Trabalho/AplicacaoRails/restaurante/app/views/motoboys/_form.html.haml
= semantic_form_for [@motoboy] do |form|
  = form.input :nome, :label => 'Nome' 
  = form.input :telefone, :label => 'Telefone'
  = form.submit 'Salvar'

Área de Trabalho/AplicacaoRails/restaurante/app/views/motoboys/edit.html.erb
<h1>Editing motoboy</h1>

<%= render 'form' %>

<%= link_to 'Show', @motoboy %> |
<%= link_to 'Back', motoboys_path %>

Área de Trabalho/AplicacaoRails/restaurante/app/views/motoboys/index.html.erb
<h1>Motoboys</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Telefone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @motoboys.each do |motoboy| %>
  <tr>
    <td><%= motoboy.nome %></td>
    <td><%= motoboy.telefone %></td>
    <td><%= link_to 'Show', motoboy %></td>
    <td><%= link_to 'Edit', (edit_motoboy_path motoboy) %></td>
    <td><%= link_to 'Excluir', motoboy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Motoboy', new_motoboy_path %>

Área de Trabalho/AplicacaoRails/restaurante/app/views/motoboys/new.html.erb
<h1>New motoboy</h1>

<%= render 'form' %>

<%= link_to 'Back', motoboys_path %>

Área de Trabalho/AplicacaoRails/restaurante/app/views/motoboys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @motoboy.nome %>
</p>

<p>
  <b>Telefone:</b>
  <%= @motoboy.telefone %>
</p>


<%= link_to 'Edit', edit_motoboy_path(@motoboy) %> |
<%= link_to 'Back', motoboys_path %>

Área de Trabalho/AplicacaoRails/restaurante/app/views/pedidos/_form.html.haml
= semantic_form_for [@pedido] do |form|

  = form.input :data, :label => 'Data'
  = form.input :hora, :label => 'Hora'
  = form.input :valor, :label => 'Valor'
  = form.input :cliente, :member_label => :nome, :label => 'Cliente'
  = form.input :motoboy, :member_label => :nome, :label => 'Motoboy'
  = form.submit 'Salvar'

Área de Trabalho/AplicacaoRails/restaurante/app/views/pedidos/edit.html.erb
<h1>Editing pedido</h1>

<%= render 'form' %>

<%= link_to 'Show', @pedido %> |
<%= link_to 'Back', pedidos_path %>

Área de Trabalho/AplicacaoRails/restaurante/app/views/pedidos/index.html.erb
<h1>Pedidos</h1>

<table>
  <tr>
    <th>Data</th>
    <th>Hora</th>
    <th>Valor</th>
    <th>Cliente</th>
    <th>Motoboy</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pedidos.each do |pedido| %>
  <tr>
    <td><%= pedido.data %></td>
    <td><%= pedido.hora %></td>
    <td><%= pedido.valor %></td>
    <td><%= pedido.cliente.nome %></td>
    <td><%= pedido.motoboy.nome %></td>
    <td><%= link_to 'Show', pedido %></td>
    <td><%= link_to 'Edit', (edit_pedido_path pedido) %></td>
    <td><%= link_to 'Excluir', pedido, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pedido', new_pedido_path %>

Área de Trabalho/AplicacaoRails/restaurante/app/views/pedidos/new.html.erb
<h1>New pedido</h1>

<%= render 'form' %>

<%= link_to 'Back', pedidos_path %>

Área de Trabalho/AplicacaoRails/restaurante/app/views/pedidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Data:</b>
  <%= @pedido.data %>
</p>

<p>
  <b>Hora:</b>
  <%= @pedido.hora %>
</p>

<p>
  <b>Valor:</b>
  <%= @pedido.valor %>
</p>

<p>
  <b>Cliente:</b>
  <%= @pedido.cliente.nome %>
</p>

<p>
  <b>Motoboy:</b>
  <%= @pedido.motoboy.nome %>
</p>


<%= link_to 'Edit', edit_pedido_path(@pedido) %> |
<%= link_to 'Back', pedidos_path %>